export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ON_SAVE_NEW_EMPLOYEE = 'ON_SAVE_NEW_EMPLOYEE';
export const ON_SAVE_NEW_EMPLOYEE_SUCCESS = 'ON_SAVE_NEW_EMPLOYEE_SUCCESS';